// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

import {Test} from "forge-std/Test.sol";

import {SessionContext, StepResult} from "../src/interfaces/ICasinoGameV2.sol";
import {RuckusGame} from "../src/RuckusGame.sol";

// Replays vectors generated by @arena/casino-math (`pnpm -F @arena/casino-math vectors`), proving the
// TS mirror and Solidity draw the same class and pay the same amount for the same VRF word (ADR-004).
contract ParityTest is Test {
    RuckusGame private game;

    function setUp() public {
        game = new RuckusGame();
    }

    function test_backChicken_matchesTsMirror() public view {
        _replay("back-chicken.json", game.BET_BACK_CHICKEN(), abi.encode(uint8(0)));
    }

    function test_callShot_matchesTsMirror() public view {
        bytes memory params = abi.encode(uint8(1), uint8(3));
        _replay("call-shot-1.json", game.BET_CALL_SHOT_STRAIGHT(), params);
        _replay("call-shot-2.json", game.BET_CALL_SHOT_CUT(), params);
        _replay("call-shot-3.json", game.BET_CALL_SHOT_THIN(), params);
        _replay("call-shot-4.json", game.BET_CALL_SHOT_LONG(), params);
    }

    function _replay(string memory file, uint8 betType, bytes memory params) private view {
        string memory json = vm.readFile(string.concat(vm.projectRoot(), "/vectors/", file));
        bytes32[] memory randomness = vm.parseJsonBytes32Array(json, ".randomness");
        uint256[] memory classes = vm.parseJsonUintArray(json, ".classes");
        string[] memory wagers = vm.parseJsonStringArray(json, ".wagers");
        string[] memory payouts = vm.parseJsonStringArray(json, ".payouts");
        (uint256[] memory weights,) = game.betTable(betType);
        bytes memory gameData = abi.encode(betType, uint8(1), params);

        assertGt(randomness.length, 0);
        for (uint256 i = 0; i < randomness.length; ++i) {
            assertEq(game.drawClass(randomness[i], weights), classes[i], "class mismatch");

            SessionContext memory ctx;
            ctx.wagerBase = vm.parseUint(wagers[i % wagers.length]);
            ctx.gameData = gameData;
            StepResult memory settle = game.onRandomness(ctx, randomness[i]);
            assertEq(settle.payout, vm.parseUint(payouts[i]), "payout mismatch");
        }
    }
}
