// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

import {Test} from "forge-std/Test.sol";

import {SessionContext, StepResult} from "../src/interfaces/ICasinoGameV2.sol";
import {RuckusGame} from "../src/RuckusGame.sol";

// Replays vectors generated by @arena/casino-math (`pnpm -F @arena/casino-math vectors`), proving the
// TS mirror and Solidity draw the same class and pay the same amount for the same VRF word (ADR-004).
contract ParityTest is Test {
    RuckusGame private game;

    function setUp() public {
        game = new RuckusGame();
    }

    function test_backChicken_matchesTsMirror() public view {
        string memory json = vm.readFile(string.concat(vm.projectRoot(), "/vectors/back-chicken.json"));
        bytes32[] memory randomness = vm.parseJsonBytes32Array(json, ".randomness");
        uint256[] memory classes = vm.parseJsonUintArray(json, ".classes");
        string[] memory wagers = vm.parseJsonStringArray(json, ".wagers");
        string[] memory payouts = vm.parseJsonStringArray(json, ".payouts");
        (uint256[] memory weights,) = game.betTable(game.BET_BACK_CHICKEN());
        bytes memory gameData = abi.encode(game.BET_BACK_CHICKEN(), uint8(1), abi.encode(uint8(0)));

        assertGt(randomness.length, 0);
        for (uint256 i = 0; i < randomness.length; ++i) {
            assertEq(game.drawClass(randomness[i], weights), classes[i], "class mismatch");

            SessionContext memory ctx;
            ctx.wagerBase = vm.parseUint(wagers[i % wagers.length]);
            ctx.gameData = gameData;
            StepResult memory settle = game.onRandomness(ctx, randomness[i]);
            assertEq(settle.payout, vm.parseUint(payouts[i]), "payout mismatch");
        }
    }
}
